### PR TITLE
[INFRA-2200] Add oleg ssh key to the aws ssh gateway

### PR DESCRIPTION
**Pull request by olblak**

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]

**Comment by lloydchang** [comment]
:+1:

**Comment by lloydchang** [comment]
FYI @markyjackson-taulia

**Comment by markjacksonfishing** [comment]
@lloydchang ?

**Comment by lloydchang** [comment]
@markyjackson-taulia sorry; I should have clarified earlier.

As you discover Jenkins INFRA and jot your notes, perhaps some documentation / run-book are available but require cross-referencing.

Information seems to spread across different locations as piecemeal sources of truth.

For example, https://issues.jenkins-ci.org INFRA-2200 needs to be supplemented by this github.com jenkins-infra #1345 pull request.

Separately, there was a prior migration described on jenkins.io
https://jenkins.io/blog/2016/05/18/announcing-azure-partnership/
> Currently we have infrastructure in four different locations, with four different infrastructure providers, each with their own APIs and tools for managing resources, each with varying capabilities and capacities.

You may have a better perspective as you plan on attending INFRA meetings to be on-boarded.

Perhaps there is one source of truth (maybe infra-as-code here in github.com?) that is centralized(?) instead of piecemeal sources of truth spread across different locations in Jira, GitHub, jenkins.io web, mailing list, IRC, etc.

I don’t have the time availability to participate in INFRA as you plan on doing; I appreciate your time and efforts.

Thank you 🙂

**Comment by olblak** [comment]
Some context here to explain why this PR was needed, @oleg-nenashev requested an access to trusted.ci which is a "trusted" Jenkins instance hidden behind a ssh gateway. We granted permission @oleg to login on trusted.ci but we were missing this part in order for him to "see" that service.

**Pull request merged**
