### PR TITLE
Enable the Blueocean plugin in our clusters

### PR DESCRIPTION
**Pull request by rtyler**

### CODE REVIEW

**Comment by abayer** [comment]
:+1: Bwahahaha, this brings in `pipeline-model-definition` at the same time. =)

**Comment by rtyler** [comment]
@abayer I would request that nobody start introducing declarative Pipelines into our infrastructure until there's bloody documentation on jenkins.io for it, otherwise we lose a valuable demonstration use

**Comment by abayer** [comment]
@rtyler I agree completely. @i386 needs to hurry up and make a PR. =)

**Comment by rtyler** [comment]
This change is now blocked because the blueocean-plugin requires 2.7.3 or later of core, which means we must upgrade the full Jenkins instance just for this

**Comment by i386** [comment]
I was just thinking about those docs today. Yes, PR is coming :)

**Pull request merged**
