### PR TITLE
[INFRA-2310] Move back to G1GC + use 16Gb of Heap

### PR DESCRIPTION
**Pull request by aheritier**
I reverted our changes of this morning because they aren't J11 compatible and it introduces a lot of changes at the same time which is making difficult to understand if they are helping or not.

### CODE REVIEW

**Comment by rtyler** [comment]
This looks fine for me, but I've been very out of the loop this week so I'll let @olblak handle this

**Comment by olblak** [comment]
Because of the limited time we had yesterday to revert this change, I disabled puppet agent on that machine and allowed @aheritier to do the quick changes needed to revert to a working state. @aheritier can you confirm that this PR represent the state of ci.jenkins.io and so can be merged

**Review by olblak — APPROVED** [review]
At least we know it worked

**Comment by aheritier** [comment]
@olblak yes I copy/paster the prod settings. I am preparing a new PR based on @dohbedoh feedback

**Pull request merged**
