### PR TITLE
Fix the language order issues

### LINKED ISSUE #38: Translate task: about/artwork

### PR DESCRIPTION
**Pull request by LinuxSuRen**
Fix jenkins-infra/cn.jenkins.io#38. Inspire from @muellert which in [here](https://github.com/jenkins-infra/cn.jenkins.io/issues/238#issuecomment-547366920).

### CODE REVIEW

**Comment by olblak** [comment]
I am not sure to understand how this regex will fix the issue, but it worth trying, thanks for this PR

**Review by olblak — APPROVED** [review]
\o/

**Comment by muellert** [comment]
> I am not sure to understand how this regex will fix the issue, but it worth trying, thanks for this PR

I haven't tried it, but the nginx docs suggest that if the expression starts with '~', it is being interpreted as a regular expression. IOW, the new regular expression should only fire if 'zh' appears at the beginning of the line. Have a look at your browser's accept-language headers. If you have only one language configured, just add another one temporarily to see the effect.

**Comment by LinuxSuRen** [comment]
@olblak It seems isn't working. I guess this fix might not be deployed yet. So could you let me know this? Or when it is ready.

**Comment by olblak** [comment]
@LinuxSuRen you are right, for some reason the second PR from staging to production wasn't trigger, I just create it

**Comment by LinuxSuRen** [comment]
It's working now! Thanks to @olblak  and @muellert .

**Pull request merged**
