### PR TITLE
Chore: enable autoupdate of ci.jenkins.io agent templates (Azure VMs + Kubernetes Agents)

### PR DESCRIPTION
**Pull request by dduportal**
This change enable automatic update (through updatecli) of the agent templates of ci.jenkins.io (Azure VMs and Kubernetes agents).

It introduces the following changes:

- Updated the existing updatecli templates (for Jenkins LTS and OpenVPN/LDAP Docker images) to remove depreciation warnings from latest updatecli versions (0.6.x)
- Add a new updatecli configuration to handle ci.jenkins.io's agent templates with support for the Azure VM (thourhg the image gallery version) and Kubernetes agents (ref. INFRA-3036)
- Execute the `updatecli diff` step (on GitHub Actions) for each PR and branch, to ensure that a change in targeted files (such as hieradata/commons.yaml), which would break updatecli, cannot be merged.

Please note that:

* This PR depends on #1833 (to ensure that all pod templates are defined in hieradata).
* The AWS EC2 agents are not automatically updated: there is some work to be done on jenkins-infra/packer-images to publish AMI ids as tags OR in `updatecli` to support an AWS provider or generic shell provider"
* Once merged, this PR will generate PR(s) to define shasum on the container images

### CODE REVIEW

**Comment by dduportal** [comment]
Setting as draft until #1833 is approved merged + a rebase is done here

**Comment by dduportal** [comment]
Ready to be reviewed!

**Review by timja — APPROVED** [review]
haven't looked closely, lots of yaml.

**Comment by dduportal** [comment]
> haven't looked closely, lots of yaml.

For info, it generated this PR: https://github.com/jenkins-infra/jenkins-infra/pull/1835

**Pull request merged**
