### PR TITLE
Removes dependency with vagrant-aws plugin

### PR DESCRIPTION
**Pull request by mpailloncy**
As per discussion with Olivier, this dependency is probably no longer required.
But Tyler might come here and say "NO NO NO NOOOOO".

### CODE REVIEW

**Review by rtyler — APPROVED** [review]
NOO NOO NOOO!

Just kidding. vagrant-aws is not particularly well-maintained anymore, and most of our machines are much more powerful than they were five years ago. :smile_cat:

**Comment by rtyler** [comment]
@olblak apparently you *must* review this too? That seems odd that all code owners must approve :slightly_frowning_face:

**Comment by olblak** [comment]
Indeed weird, I can merge without approving, I'll review merge settings

**Comment by rtyler** [comment]
Used my administrator privileges to merge.

**Pull request merged**
