### PR TITLE
Allow accessing the hosting plugins page

### PR DESCRIPTION
**Pull request by timja**
Oleg said there's some missing content to be migrated

### CODE REVIEW

**Comment by halkeye** [comment]
I would just remove the redirect for now? @oleg-nenashev do you want full access for everyone, or just the wiki exporter to be able to dump content?

**Comment by timja** [comment]
> I would just remove the redirect for now? @oleg-nenashev do you want full access for everyone, or just the wiki exporter to be able to dump content?

image

It's in a thread on gitter, you might not be able to see it in your irc bridge

**Comment by halkeye** [comment]
No I saw it, I took it as "Remove the redirect so people can see the missing content" not "Allow content to be fetched from wiki exporter so we can move more content"

**Comment by timja** [comment]
> No I saw it, I took it as "Remove the redirect so people can see the missing content" not "Allow content to be fetched from wiki exporter so we can move more content"

k, I would rather just migrate it, but I don't know what's left...

**Comment by halkeye** [comment]
Yea, I much rather migrate too, but until it is migrated, I think it should be opened up.

**Review by olblak — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Thanks all!

**Pull request merged**
