### PR TITLE
cleanup: remove users who do not access the infra anymore

### PR DESCRIPTION
**Pull request by dduportal**
This PR removes users who are not participating in the infra anymore.

Of course if i'm mistaken, please send a message or a PR and we'll re-enable your accesses!

----

Technical note: this PR will not remove the user accounts: it has to be done manually on all machines

### CODE REVIEW

**Review by timja — DISMISSED** [review]

**Comment by dduportal** [comment]
In order to cleanup users, I run the following command:

```
for machine in ci.jenkins.io cert.ci.jenkins.io archives.jenkins.io pkg.origin.jenkins.io edamame.jenkins.io lettuce.jenkins.io census.jenkins.io usage.jenkins.io controller.trusted.ci.jenkins.io agent.trusted.ci.jenkins.io vpn.jenkins.io private.vpn.jenkins.io bounce.trusted.ci.jenkins.io puppet.jenkins.io; do echo "=== Machine: ${machine}";ssh "${machine}" sudo deluser garethjevans;done
```

**Review by MarkEWaite — DISMISSED** [review]

**Comment by MarkEWaite** [comment]
I thought that @abayer was still generating the monthly reports for stats.jenkins.io.  If he is generating those reports, I assume he is accessing some part of the infrastructure to collect the data.

You may want to check with @batmat for the current status.

**Comment by lemeurherve** [comment]
@batmat WDYT?

**Review by MarkEWaite — DISMISSED** [review]
I believe that @abayer is still generating the monthly reports, though I don't have any reason to believe that requires access to Jenkins infrastructure.;

**Comment by timja** [comment]
> I believe that @abayer is still generating the monthly reports, though I don't have any reason to believe that requires access to Jenkins infrastructure.;

it does as far as I know, I would hold off on this PR until confirmed

**Comment by abayer** [comment]
Yup, I need ssh access to usage.jenkins.io.

**Comment by dduportal** [comment]
Thanks for the careful reviews!
I've updated the PR to let @abayer accessing `usage.jenkins.io`.

**Review by MarkEWaite — APPROVED** [review]

**Pull request merged**
