### PR TITLE
Accountapp: Enable Cookie Session affinity

### PR DESCRIPTION
**Pull request by olblak**

### CODE REVIEW

**Comment by olblak** [comment]
@rtyler I am not sure to understand why the latest commit is needed ( e92cece )

**Review by rtyler — DISMISSED** [review]
@olblak it's not, and never should be. merging *only* ever is in the direction of `staging` :arrow_right: `production`.

**Comment by olblak** [comment]
It's well what I was thinking 
@rtyler What do you suggest for this PR? 
It's already in staging (I updated staging from this PR by mistake ) so should I undo the branch merge or do we stay like this?

**Comment by rtyler** [comment]
Fine, but please stop merging and smashing code around into repositories now that you have the access to.

**Pull request merged**
