### PR TITLE
IRC bot build 50

### PR DESCRIPTION
**Pull request by jglick**
Deploys https://github.com/jenkins-infra/ircbot/commit/6b67e8612cc572aa4129b450eda5ddc34823c8a8 to integrate https://github.com/kohsuke/github-api/pull/245. CC @daniel-beck, @rtyler

### CODE REVIEW

**Comment by jglick** [comment]
as per [instructions](https://github.com/jenkins-infra/ircbot/blob/9e7454f942b0b683ea05c8fe88659b2be156633b/README.md#deployment) amended by https://github.com/jenkins-infra/ircbot/pull/26 & https://github.com/jenkins-infra/ircbot/pull/27

**Comment by jglick** [comment]
@reviewbybees just in case

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by jglick** [comment]
Note that https://github.com/jenkinsci/workflow-step-api-plugin actually got created, but I do not know whether it is properly set up or not. Does someone need to manually fix up its hooks? I do not seem to have admin access to it to check.

**Comment by jtnord** [comment]
:bee: as far as I understand it.

**Comment by rtyler** [comment]
Due to on-going work in [INFRA-576](https://issues.jenkins-ci.org/browse/INFRA-576) this will need to be manually deployed, so I will update this once it is in production

**Comment by rtyler** [comment]
build50 is live in production

**Pull request merged**
