### PR TITLE
Redirect "Reverse Proxy Configuation with Jenkins" from Wiki to Jenkins.io

### PR DESCRIPTION
**Pull request by zaycodes**

### CODE REVIEW

**Comment by olblak** [comment]
While the PR is fine to me, can I ask you to cleanup the git history ?

**Comment by MarkEWaite** [comment]
@zaycodes it appears that your force push may have removed the content you intended to include in the pull request.  I was able to reconstruct what I believe you intended to commit with the commands:

```
$ git fetch origin
$ git checkout -b origin-staging -t origin/staging
$ git cherry-pick b50bb2fd5ac12d30acf136d0b50268b91773c509
```

The final command, `git cherry-pick` , relies on being able to find the commit b50bb2fd5ac12d30acf136d0b50268b91773c509 that you had before the force push.  In case it has been removed from your local repository, you can find a copy of it at https://github.com/MarkEWaite/jenkins-infra/commit/a82f050eb68013d73b9decf80baf21be5ef43239 .

If you'd like additional help with the necessary git commands, they would be a great topic for Docs office hours this week.

**Comment by zaycodes** [comment]
Thanks @MarkEWaite, is it fine now?, how can cleanup git history without losing the intended changes as suggested by @olblak.

**Comment by olblak** [comment]
> Thanks @MarkEWaite, is it fine now?, how can cleanup git history without losing the intended changes as suggested by @olblak.

The easiest way is to create a new branch based on this upstream from staging branch then you cherry-pick the commit you are looking for and finallyl open a new PR.

```
git remote add upstream git@github.com:jenkins-infra/jenkins-infra.git
git checkout upstream/staging
git checkout -b new_branch_name
git cherry-pick 11a7dac053e2380676c5304048b9f3fa61a17b1f
git push --set-upstream origin <new_branch_name>
```

Another option is to rebase your current branch from upstream/staging
```
git remote add upstream git@github.com:jenkins-infra/jenkins-infra.git
git rebase upstream/staging
# resolve conflicts
git push --force
```

**Comment by MarkEWaite** [comment]
> Thanks @MarkEWaite, is it fine now?, how can cleanup git history without losing the intended changes as suggested by @olblak.

The suggestions from @olblak will clean the git history or you can close this pull request, create a new branch, cherry pick the change to that new branch and submit the new pull request to supersede this one.

**Comment by olblak** [comment]
> The suggestions from @olblak will clean the git history or you can close this pull request, create a new branch, cherry pick the change to that new branch and submit the new pull request to supersede this one.

The second suggestion indeed, but the first  part suggest exactly that :trollface:

**Pull request merged**
