### PR TITLE
feat(pkg) add jenkins-infra/mirrorscripts under Puppet management

### PR DESCRIPTION
**Pull request by dduportal**
Follow up of https://github.com/jenkins-infra/helpdesk/issues/3414

This PR is the first step of https://github.com/jenkins-infra/jenkins-infra/issues/3352.

It adds the set of "mirror scripts" used on the `pkg` VM (pkg.origin.jenkins.io and updates.jenkins.io) under Puppet management but without any templated content (subsequent PR):

- The repository [jenkins-infra/mirror-scripts](https://github.com/jenkins-infra/mirror-scripts) was imported into `dist/profile/templates/mirror-scripts` with all its history using the following command (note: [7184a97f1a2591684f6b5b32abaf7ff5efb1dfd3](https://github.com/jenkins-infra/mirror-scripts/commit/7184a97f1a2591684f6b5b32abaf7ff5efb1dfd3) being the HEAD of its `main` branch):

  ```bash
  git subtree add -P dist/profile/templates/mirror-scripts https://github.com/jenkins-infra/mirror-scripts 7184a97f1a2591684f6b5b32abaf7ff5efb1dfd3
  ```

  - Note that any `git log` command in the future will see the imported reference files at the root of jenkins-infra/jenkins-infra so might need addition options. But a subsequent PR will have the script renamed with a `.erb` extension.

- There is **only** one commit to be review: the last one [e8a6aebf69ae0898f44cdabf3a8e052e3e5d0302](https://github.com/jenkins-infra/jenkins-infra/pull/3358/commits/e8a6aebf69ae0898f44cdabf3a8e052e3e5d0302) which has the puppet management code.
  -  Note that the file content uses the `template()` function but no templated content is available yet!
  - The `.gitignore` and the `README.md` files have been removed from `mirror-scripts`

The following workflow is expected once this PR is approved (or if a "force merge" is triggered) - tested on a local vagrant VM 

- **before** merging:
  - Run the puppet agent on the VM one last time to ensure the "noop" diff won't be polluted by the usual Jenkins keys regular changes (will be fixed on another PR)
  - Disabling puppet agent **before** on the `pkg` VM
- Merge the PR here
- Run a puppet agent "noop" and make sure that only the changes here are expected, then apply
  -Note: We only expect the 6 symlinks to be replaced by files
- Compare the content of the 6 new files with the content of their counterparts in `/srv/releases/mirror-scripts/`. They should be the **same**
- If OK, then delete the directory `/srv/releases/mirror-scripts` and the `/srv/releases/.git*` config file (if any)
- Restart the pupept agent and check there are no changes

### CODE REVIEW

**Comment by lemeurherve** [comment]
WDYT of rebasing some of the recent commits?

**Comment by dduportal** [comment]
> WDYT of rebasing some of the recent commits?

I'm not sure to understand: what is the problem it would solve? Not sure how to do it either?

**Comment by lemeurherve** [comment]
Sorry, by rebasing I meant squashing commits so the git (recent) history would be a little bit cleaner and easier to navigate if needed.

**Comment by MarkEWaite** [comment]
> Sorry, by rebasing I meant squashing commits so the git (recent) history would be a little bit cleaner and easier to navigate if needed.

I'm opposed to rebase or squash of changes on the primary branch of a repository because it requires others who have forked or cloned the repository to perform additional actions to replace the history that is being rewritten.  That is especially problematic when `git clone` is used to populate a tools collection onto a machine.  I do that with agents in my private Jenkins controller and it would be a terrible experience if I changed the existing history of the primary branch.

I don't object to squash or rebase during a merge operation.  That tends to keep the history of the primary branch more tidy. However, once something is on the primary branch, a rewrite of history creates pain for others.

**Comment by lemeurherve** [comment]
> > Sorry, by rebasing I meant squashing commits so the git (recent) history would be a little bit cleaner and easier to navigate if needed.
> 
> I'm opposed to rebase or squash of changes on the primary branch of a repository because it requires others who have forked or cloned the repository to perform additional actions to replace the history that is being rewritten. That is especially problematic when `git clone` is used to populate a tools collection onto a machine. I do that with agents in my private Jenkins controller and it would be a terrible experience if I changed the existing history of the primary branch.
> 
> I don't object to squash or rebase during a merge operation. That tends to keep the history of the primary branch more tidy. However, once something is on the primary branch, a rewrite of history creates pain for others.

As these commits aren't in this repo yet I'm proposing to take the opportunity of this PR to squash some of these.
No one should be impacted by this as there is no rebase or squash of any commit of the primary branch, only on commits of this pull request.

**Comment by dduportal** [comment]
> > > Sorry, by rebasing I meant squashing commits so the git (recent) history would be a little bit cleaner and easier to navigate if needed.
> > 
> > 
> > I'm opposed to rebase or squash of changes on the primary branch of a repository because it requires others who have forked or cloned the repository to perform additional actions to replace the history that is being rewritten. That is especially problematic when `git clone` is used to populate a tools collection onto a machine. I do that with agents in my private Jenkins controller and it would be a terrible experience if I changed the existing history of the primary branch.
> > I don't object to squash or rebase during a merge operation. That tends to keep the history of the primary branch more tidy. However, once something is on the primary branch, a rewrite of history creates pain for others.
> 
> As these commits aren't in this repo yet I'm proposing to take the opportunity of this PR to squash some of these. No one should be impacted by this as there is no rebase or squash of any commit of the primary branch, only on commits of this pull request.

The goal of importing the history is to allow navigating through the `git` CLI instead of having to search GitHub (https://github.com/jenkins-infra/mirror-scripts/commits/main/). It means the history should be kept to map to the existing (almost archived) repository otherwise I don't see the need.

Rewriting the imported history has an impact: it will be hard to map a given change to the associated history in https://github.com/jenkins-infra/mirror-scripts.

Besides, what would the criteria to decide to rebase or not? Who would have to do this? It looks like a superficial change and that means spending hours getting a review + consensus on each squashed commit. I don't see the problem being solved by doing this, but only the waste of time. Could you clarify your request in that matter?

**Comment by dduportal** [comment]
Starting a pairing session with @smerle33 to land this PR and process forward.

We'll merge with the option "Merge commit" to avoid polluting the main branch's history. The `git log` will still be able to search the imported history through the ref-log, but we won't have what appear to be an annoyance regarding the collection of commits.

**Review by smerle33 — APPROVED** [review]
LGTM 🚀

**Comment by dduportal** [comment]
Deployment went well (following the written procedure).

**Pull request merged**
