### PR TITLE
Add coverage-badges-extension plugin on ci.jenkins.io

### PR DESCRIPTION
**Pull request by jonesbusy**
See https://github.com/jenkins-infra/helpdesk/issues/3879

### CODE REVIEW

**Comment by NotMyFault** [comment]
ref https://github.com/jenkins-infra/helpdesk/issues/3879 for linking

I've started a build on infra.ci :)

**Review by dduportal — DISMISSED** [review]
I would like a second guess from the @jenkins-infra/security team as ci.jenkins.io is a public instance.

Besides, note that this plugin must be ready to handle the workload we have on ci.jenkins.io. It's not extreme but clearly has some builds ;)

**Comment by jonesbusy** [comment]
Rebased because of this commit https://github.com/jenkins-infra/jenkins-infra/commit/55199da32e82a60b3e792686851d75d2553131ac

**Review by dduportal — APPROVED** [review]

**Comment by dduportal** [comment]
Triggered a new build (fyi)

**Review by NotMyFault — APPROVED** [review]

**Comment by dduportal** [comment]
More details on https://github.com/jenkins-infra/helpdesk/issues/3879#issuecomment-1874905777: we can proceed!

**Pull request merged**
