### PR TITLE
Have Jenkins perform DNS zone file syntax check 

### PR DESCRIPTION
**Pull request by kohsuke**
Added rake task to perform syntax check on DNS zone file, and have
Jenkins test it all the time.

### CODE REVIEW

**Comment by kohsuke** [comment]
Ouch, DEV@cloud build slaves cannot run Docker.

**Comment by rtyler** [comment]
"I made a docker container for this" doesn't make any sense to me. Can we not just install `named-checkzone` at runtime in Jenkins and execute that?

**Comment by kohsuke** [comment]
If this runs on ci.jenkins-ci.org we could have added all the tools, but adding custom tools isn't very easy on jenkins.ci.cloudbees.com unless we bring in our own slave, which might be what we should do.

**Comment by rtyler** [comment]
The problem that I have with this approach is that it's something I'll never do locally, and I can't reasonable make it a dependency on the `spec` task :/

**Comment by rtyler** [comment]
@kohsuke I was thinking a serverspec test might be a good way to get this done too

**Comment by kohsuke** [comment]
test via serverspec is easy to add, but now I tend not to run it locally, and Jenkins certainly doesn't do it!

**Pull request merged**
