### PR TITLE
Remove BO from trusted.ci

### PR DESCRIPTION
**Pull request by NotMyFault**
Following the ongoing cleanup

### CODE REVIEW

**Review by timja — COMMENTED** [review]
I don't think we need to remove from here. weekly sure, but blueocean still has the easiest to use visualisation for viewing logs imo.

**Comment by NotMyFault** [comment]
> I don't think we need to remove from here. weekly sure, but blueocean still has the easiest to use visualisation for viewing logs imo.

Isn't the pipeline stage view plugin enough to view logs on a per-node basis?

**Comment by timja** [comment]
> > I don't think we need to remove from here. weekly sure, but blueocean still has the easiest to use visualisation for viewing logs imo.
> 
> Isn't the pipeline stage view plugin enough to view logs on a per-node basis?

it's awful no thanks

**Comment by NotMyFault** [comment]
> > > I don't think we need to remove from here. weekly sure, but blueocean still has the easiest to use visualisation for viewing logs imo.
> > 
> > 
> > Isn't the pipeline stage view plugin enough to view logs on a per-node basis?
> 
> it's awful no thanks

I mean pipeline graph view, oops

**Comment by timja** [comment]
> I mean pipeline graph view, oops

Somewhat, I still prefer Blueocean on a day to day basis, I find it easier to use going straight into the logs

**Comment by dduportal** [comment]
> > I mean pipeline graph view, oops
> 
> Somewhat, I still prefer Blueocean on a day to day basis, I find it easier to use going straight into the logs

Same here, for the exact same reason. Somehow, if there was a link between the classic "steps" view and its "per-step output" with the pipeline-graph viewer in classic view, that would be nice.

**Pull request closed without merging**
