### PR TITLE
Ircbot deploy

### PR DESCRIPTION
**Pull request by rtyler**
Deploying the changes from:
- https://github.com/jenkins-infra/ircbot/pull/23
- https://github.com/jenkins-infra/ircbot/pull/22

### CODE REVIEW

**Comment by batmat** [comment]
Not sure I see the link between the first commit and the PR subject :-). Did you include it by mistake maybe?

**Comment by rtyler** [comment]
@batmat Whoops! I thought I had already rolled that change in from my local master branch.

**Comment by batmat** [comment]
Technical question: I know only Ansible. IIUC puppet works with a central
server that will continually check things are up to date, right? So that
basically means that merging a PR will be like running an ansible playbook
or a chef recipe?

Thanks

2016-01-07 20:27 GMT+01:00 R. Tyler Croy notifications@github.com:

**Comment by rtyler** [comment]
@batmat Puppet supports a "masterless" model (no central server) and a Puppet master model (central server). We currently use a centralized server with Puppet Enterprise which gives us additional reporting/traceability over the decentralized setup (I talk a bit about that in [this talk](https://www.youtube.com/watch?v=3hqLGKa4QwA))

The way deployments occur can be read about in the [readme](https://github.com/jenkins-infra/jenkins-infra#branching-model). At FOSDEM I'll be happy to explain anything you want to know :)

**Comment by batmat** [comment]
Thanks! (but again, as much as I would like to, I _won't_ be at FOSDEM :)).

2016-01-07 22:13 GMT+01:00 R. Tyler Croy notifications@github.com:

**Comment by rtyler** [comment]
sudo send --user=@batmat --to=fosdem

**Pull request merged**
