### PR TITLE
[INFRA-1180] Caching proxy for repo.jenkins-ci.org

### PR DESCRIPTION
**Pull request by olblak**
This PR introduce Kubernetes configuration files for a caching proxy in front of repo.jenkins-ci.org
Before merging this PR, we need:

- [x] Add shared disk storage [Azure - #26](https://github.com/jenkins-infra/azure/pull/26)
- [x] Add repo-proxy to Jenkins-infra project Move [olblak/repo-proxy](https://github.com/olblak/repo-proxy) to [jenkins-infra/repo-proxy](https://github.com/jenkins-infra/repo-proxy)
- [x] Need a docker image called jenkinsciinfra/repo-proxy
- [x] Add DNS record repo.azure.jenkins.io && repo.azure.jenkins-ci.org (included in this PR)
- [ ] Add to hiera config, name and key to connect to storage account  "prodrepoproxy''
```
profile::kubernetes::resources::repo_proxy::storage_account_name 
profile::kubernetes::resources::repo_proxy::storage_account_key
```

### CODE REVIEW

**Review by rtyler — COMMENTED** [review]
This looks promising, one note however, I think this should default to HTTPs rather than HTTP only.

**Comment by olblak** [comment]
HTTPS is handled by ingress controller which by default redirect to https if available [Doc](https://github.com/kubernetes/ingress/tree/master/controllers/nginx#server-side-https-enforcement)

**Comment by rtyler** [comment]
There are still test failures with this PR :frowning:

**Comment by olblak** [comment]
😦 Shame on me.
Test Fixed

**Comment by rtyler** [comment]
@olblak does this mean the PR is no longer "work in progress":

**Comment by olblak** [comment]
The only thing missing is 

profile::kubernetes::resources::repo_proxy::storage_account_name 
profile::kubernetes::resources::repo_proxy::storage_account_key

**Pull request merged**
