### PR TITLE
feat: use Jenkins Infra inbound-agent Windows Docker image

### PR DESCRIPTION
**Pull request by lemeurherve**
Ref: https://github.com/jenkins-infra/helpdesk/issues/2873

### CODE REVIEW

**Review by dduportal — APPROVED** [review]
👏

**Comment by dduportal** [comment]
I let you merge once you are ready: please keep an eye on the builds on ci.jenkins.io (ideally, select a plugin that would define a windows build on ACI)

**Comment by lemeurherve** [comment]
Found a potentially good candidate: https://github.com/jenkinsci/datadog-plugin/blob/master/Jenkinsfile

**Comment by lemeurherve** [comment]
✅ Test build: https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fdatadog-plugin/detail/master/41/pipeline

**Comment by dduportal** [comment]
Great job 👏

**Pull request merged**
